services:
  - type: web
    name: inventory-api
    env: node
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://dashing-sunburst-937eb9.netlify.app/
    healthCheckPath: /health
